### ISSUE TITLE
Color of the menu bar icon IN macOS Big Sur

### ISSUE THREAD

**Issue by tchek** [relikd/baRSS#7]
Hi,

The tint color of the menu bar icon in Big Sur do not work, it is always black when i select "Tint menu bar icon on unread" in Appearance. In Catalina it is ok
Thanks for the lights if any solution :-)
Cheers and take care

Tchek

**Comment by relikd** [comment]
Hi Tchek, 

unfortunately I won't update to Big Sur on my private machine until the network bypass / Apple whitelist issue is resolved. Too much of a privacy risk … That said, I will get hands on a M1 Bug Sur (typo intentional) at work in the next couple of weeks. Then I'll be able to track down this bug eventually.

Meanwhile we can try to isolate the problem together. Remote debugging so to speak 😄 
Does individual menu entries are highlighted with the correct color, or are they also just black? (you can hold down the Alt/Option key and click on a menu entry to mark it unread)

Another thing to try, if you set the menu bar icon tint color directly, changes that a thing?

```
defaults write de.relikd.baRSS colorStatusIconTint -string "#37F"
```

Make sure to quit and restart baRSS. If it does not help you can reset it afterwards with:

```
defaults delete de.relikd.baRSS colorStatusIconTint
```

And last question, are there other apps in Bug Sur that allow color highlighting? Maybe Apple removed the functionality altogether? I dont assume so, but it might very well be the case.

**Comment by tchek** [comment]
Hi **relikd**

Thanks for your fast answer 👍 

Off course i have try this 👍 

`defaults write de.relikd.baRSS colorStatusIconTint -string "#37F"`

But The menu icon stay black

For the  individual menu entries they are highlighted with the correct color, PINK, but i cannot change them too

This : `defaults write de.relikd.baRSS colorUnreadIndicator -string "#045cc5"`, do not work

At the moment the only work around i have found is to unchek "Tint menu bar icon on unread" under Appearance and i have a white Appearance which is acceptable

For the other apps in Bug Sur that allow color highlighting, i don't know ....

Cheers ;-)

**Comment by relikd** [comment]
That is strange. Btw. you found another bug. Currently, the unread entries use the same color as the bar icon. I'll fix that with the next release. But back to the original bug. If you change the color with `colorStatusIconTint` does the unread entry color changes? Or does it stay the same like system appearance? (due to the bug mentioned before, for me it changes both colors, menu icon and unread entries)

**Comment by relikd** [comment]
A shot in the dark: Can you try this version and see if it fixes the menu bar icon color?
[baRSS Beta 1.1.2 test-1.zip](https://github.com/relikd/baRSS/files/5608162/baRSS.Beta.t1.zip)

**Comment by tchek** [comment]
when i change the color with colorStatusIconTint  it stay the same like system appearance yes ...

I test the shot and tell u ...

**Comment by tchek** [comment]
Same issue with the "1.1.2 test-1"

**Comment by relikd** [comment]
> when i change the color with `colorStatusIconTint` it stay the same like system appearance yes ... No effect

That is _very_ strange. It takes the system appearance only if there is no defaults value. Did you restart the app inbetween?
Also, you cant test the test-1 version with the same `defaults write` statements, you would need to use `de.relikd.baRSS.beta` instead. And, I fixed the `colorUnreadIndicator` in the beta, so it should work as expected ...

If you tested the latest 1.1.1 release with `colorStatusIconTint` and app restart then I am honestly impressed how this – using sys-appearance even though you set it differently – works at all. According to the code it shouldn't. Or the defaults is not read.

Here is another version to test. This is a workaround to the issue. Instead of using a templated image (which looks nicer) it uses a colored icon. Let me know if it is colored.

[baRSS Beta test-2.zip](https://github.com/relikd/baRSS/files/5608585/baRSS.Beta.t2.zip)

with this version you can also try
```
defaults write de.relikd.baRSS.beta colorStatusIconTint -string "#F00"
```

**Comment by tchek** [comment]
It takes the system appearance (only the dot, not the menu icon, ) when `defaults delete de.relikd.baRSS colorStatusIconTint`is apply.

I restart the app inbetween yes.

I test with the 1.1.1 yes 👍 

I give a test to the beta test-2 and let  you know relikd

**Comment by tchek** [comment]
Yeaaaaaa; i'm impressed :-)

This "baRSS Beta test-2" take takes the system appearance with the dot AND the menu icon , that's a good start ;-)

I have to restart the app inbetween off course it is not on the fly ;-)

**Comment by relikd** [comment]
Will look at the issue more closely once I have a Mac with Bug Sur at hand. In the meantime, I've uploaded the new release.

**Comment by tchek** [comment]
Thanks **relikd** 

I can managed now with my colors ;-)

**Comment by relikd** [comment]
Status update: actual icon tinting seems to be broken in Bug Sur (https://developer.apple.com/forums/thread/666539). And I don't think Apple is capable of fixing such bugs in the same major release (at least thats my experience, they don't care about smaller bugs as this bug is prevalent since a few minor releases now). My prediction for the future: it will still be broken in macOS 12 but thats a wild guess (and a rant about Apple).

Anyway, the current workaround works fine so I'll close this issue for now.
